package com.yl.recon.core.entity.order;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AccountOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public AccountOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(Long value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(Long value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(Long value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(Long value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(Long value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<Long> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<Long> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(Long value1, Long value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(Long value1, Long value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andAccountNoIsNull() {
            addCriterion("ACCOUNT_NO is null");
            return (Criteria) this;
        }

        public Criteria andAccountNoIsNotNull() {
            addCriterion("ACCOUNT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAccountNoEqualTo(String value) {
            addCriterion("ACCOUNT_NO =", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotEqualTo(String value) {
            addCriterion("ACCOUNT_NO <>", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoGreaterThan(String value) {
            addCriterion("ACCOUNT_NO >", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_NO >=", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLessThan(String value) {
            addCriterion("ACCOUNT_NO <", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_NO <=", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLike(String value) {
            addCriterion("ACCOUNT_NO like", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotLike(String value) {
            addCriterion("ACCOUNT_NO not like", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoIn(List<String> values) {
            addCriterion("ACCOUNT_NO in", values, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotIn(List<String> values) {
            addCriterion("ACCOUNT_NO not in", values, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoBetween(String value1, String value2) {
            addCriterion("ACCOUNT_NO between", value1, value2, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT_NO not between", value1, value2, "accountNo");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeIsNull() {
            addCriterion("TRADE_ORDER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeIsNotNull() {
            addCriterion("TRADE_ORDER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeEqualTo(String value) {
            addCriterion("TRADE_ORDER_CODE =", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeNotEqualTo(String value) {
            addCriterion("TRADE_ORDER_CODE <>", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeGreaterThan(String value) {
            addCriterion("TRADE_ORDER_CODE >", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_ORDER_CODE >=", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeLessThan(String value) {
            addCriterion("TRADE_ORDER_CODE <", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_ORDER_CODE <=", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeLike(String value) {
            addCriterion("TRADE_ORDER_CODE like", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeNotLike(String value) {
            addCriterion("TRADE_ORDER_CODE not like", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeIn(List<String> values) {
            addCriterion("TRADE_ORDER_CODE in", values, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeNotIn(List<String> values) {
            addCriterion("TRADE_ORDER_CODE not in", values, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeBetween(String value1, String value2) {
            addCriterion("TRADE_ORDER_CODE between", value1, value2, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeNotBetween(String value1, String value2) {
            addCriterion("TRADE_ORDER_CODE not between", value1, value2, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTransTypeIsNull() {
            addCriterion("TRANS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTransTypeIsNotNull() {
            addCriterion("TRANS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTransTypeEqualTo(String value) {
            addCriterion("TRANS_TYPE =", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotEqualTo(String value) {
            addCriterion("TRANS_TYPE <>", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeGreaterThan(String value) {
            addCriterion("TRANS_TYPE >", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TRANS_TYPE >=", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeLessThan(String value) {
            addCriterion("TRANS_TYPE <", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeLessThanOrEqualTo(String value) {
            addCriterion("TRANS_TYPE <=", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeLike(String value) {
            addCriterion("TRANS_TYPE like", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotLike(String value) {
            addCriterion("TRANS_TYPE not like", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeIn(List<String> values) {
            addCriterion("TRANS_TYPE in", values, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotIn(List<String> values) {
            addCriterion("TRANS_TYPE not in", values, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeBetween(String value1, String value2) {
            addCriterion("TRANS_TYPE between", value1, value2, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotBetween(String value1, String value2) {
            addCriterion("TRANS_TYPE not between", value1, value2, "transType");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Double value) {
            addCriterion("AMOUNT =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Double value) {
            addCriterion("AMOUNT <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Double value) {
            addCriterion("AMOUNT >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("AMOUNT >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Double value) {
            addCriterion("AMOUNT <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Double value) {
            addCriterion("AMOUNT <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Double> values) {
            addCriterion("AMOUNT in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Double> values) {
            addCriterion("AMOUNT not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Double value1, Double value2) {
            addCriterion("AMOUNT between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Double value1, Double value2) {
            addCriterion("AMOUNT not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andFundSymbolIsNull() {
            addCriterion("FUND_SYMBOL is null");
            return (Criteria) this;
        }

        public Criteria andFundSymbolIsNotNull() {
            addCriterion("FUND_SYMBOL is not null");
            return (Criteria) this;
        }

        public Criteria andFundSymbolEqualTo(String value) {
            addCriterion("FUND_SYMBOL =", value, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolNotEqualTo(String value) {
            addCriterion("FUND_SYMBOL <>", value, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolGreaterThan(String value) {
            addCriterion("FUND_SYMBOL >", value, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("FUND_SYMBOL >=", value, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolLessThan(String value) {
            addCriterion("FUND_SYMBOL <", value, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolLessThanOrEqualTo(String value) {
            addCriterion("FUND_SYMBOL <=", value, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolLike(String value) {
            addCriterion("FUND_SYMBOL like", value, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolNotLike(String value) {
            addCriterion("FUND_SYMBOL not like", value, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolIn(List<String> values) {
            addCriterion("FUND_SYMBOL in", values, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolNotIn(List<String> values) {
            addCriterion("FUND_SYMBOL not in", values, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolBetween(String value1, String value2) {
            addCriterion("FUND_SYMBOL between", value1, value2, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andFundSymbolNotBetween(String value1, String value2) {
            addCriterion("FUND_SYMBOL not between", value1, value2, "fundSymbol");
            return (Criteria) this;
        }

        public Criteria andTransTimeIsNull() {
            addCriterion("TRANS_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTransTimeIsNotNull() {
            addCriterion("TRANS_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTransTimeEqualTo(Date value) {
            addCriterion("TRANS_TIME =", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeNotEqualTo(Date value) {
            addCriterion("TRANS_TIME <>", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeGreaterThan(Date value) {
            addCriterion("TRANS_TIME >", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TRANS_TIME >=", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeLessThan(Date value) {
            addCriterion("TRANS_TIME <", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeLessThanOrEqualTo(Date value) {
            addCriterion("TRANS_TIME <=", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeIn(List<Date> values) {
            addCriterion("TRANS_TIME in", values, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeNotIn(List<Date> values) {
            addCriterion("TRANS_TIME not in", values, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeBetween(Date value1, Date value2) {
            addCriterion("TRANS_TIME between", value1, value2, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeNotBetween(Date value1, Date value2) {
            addCriterion("TRANS_TIME not between", value1, value2, "transTime");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNull() {
            addCriterion("SYSTEM_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNotNull() {
            addCriterion("SYSTEM_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeEqualTo(String value) {
            addCriterion("SYSTEM_CODE =", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotEqualTo(String value) {
            addCriterion("SYSTEM_CODE <>", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThan(String value) {
            addCriterion("SYSTEM_CODE >", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SYSTEM_CODE >=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThan(String value) {
            addCriterion("SYSTEM_CODE <", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThanOrEqualTo(String value) {
            addCriterion("SYSTEM_CODE <=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLike(String value) {
            addCriterion("SYSTEM_CODE like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotLike(String value) {
            addCriterion("SYSTEM_CODE not like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIn(List<String> values) {
            addCriterion("SYSTEM_CODE in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotIn(List<String> values) {
            addCriterion("SYSTEM_CODE not in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeBetween(String value1, String value2) {
            addCriterion("SYSTEM_CODE between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotBetween(String value1, String value2) {
            addCriterion("SYSTEM_CODE not between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeIsNull() {
            addCriterion("BUSSINESS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeIsNotNull() {
            addCriterion("BUSSINESS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeEqualTo(String value) {
            addCriterion("BUSSINESS_CODE =", value, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeNotEqualTo(String value) {
            addCriterion("BUSSINESS_CODE <>", value, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeGreaterThan(String value) {
            addCriterion("BUSSINESS_CODE >", value, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("BUSSINESS_CODE >=", value, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeLessThan(String value) {
            addCriterion("BUSSINESS_CODE <", value, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeLessThanOrEqualTo(String value) {
            addCriterion("BUSSINESS_CODE <=", value, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeLike(String value) {
            addCriterion("BUSSINESS_CODE like", value, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeNotLike(String value) {
            addCriterion("BUSSINESS_CODE not like", value, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeIn(List<String> values) {
            addCriterion("BUSSINESS_CODE in", values, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeNotIn(List<String> values) {
            addCriterion("BUSSINESS_CODE not in", values, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeBetween(String value1, String value2) {
            addCriterion("BUSSINESS_CODE between", value1, value2, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andBussinessCodeNotBetween(String value1, String value2) {
            addCriterion("BUSSINESS_CODE not between", value1, value2, "bussinessCode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andReconDateIsNull() {
            addCriterion("RECON_DATE is null");
            return (Criteria) this;
        }

        public Criteria andReconDateIsNotNull() {
            addCriterion("RECON_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andReconDateEqualTo(Date value) {
            addCriterionForJDBCDate("RECON_DATE =", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("RECON_DATE <>", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateGreaterThan(Date value) {
            addCriterionForJDBCDate("RECON_DATE >", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RECON_DATE >=", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateLessThan(Date value) {
            addCriterionForJDBCDate("RECON_DATE <", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RECON_DATE <=", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateIn(List<Date> values) {
            addCriterionForJDBCDate("RECON_DATE in", values, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("RECON_DATE not in", values, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RECON_DATE between", value1, value2, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RECON_DATE not between", value1, value2, "reconDate");
            return (Criteria) this;
        }

        public Criteria andIsFeeIsNull() {
            addCriterion("IS_FEE is null");
            return (Criteria) this;
        }

        public Criteria andIsFeeIsNotNull() {
            addCriterion("IS_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andIsFeeEqualTo(String value) {
            addCriterion("IS_FEE =", value, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeNotEqualTo(String value) {
            addCriterion("IS_FEE <>", value, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeGreaterThan(String value) {
            addCriterion("IS_FEE >", value, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeGreaterThanOrEqualTo(String value) {
            addCriterion("IS_FEE >=", value, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeLessThan(String value) {
            addCriterion("IS_FEE <", value, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeLessThanOrEqualTo(String value) {
            addCriterion("IS_FEE <=", value, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeLike(String value) {
            addCriterion("IS_FEE like", value, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeNotLike(String value) {
            addCriterion("IS_FEE not like", value, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeIn(List<String> values) {
            addCriterion("IS_FEE in", values, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeNotIn(List<String> values) {
            addCriterion("IS_FEE not in", values, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeBetween(String value1, String value2) {
            addCriterion("IS_FEE between", value1, value2, "isFee");
            return (Criteria) this;
        }

        public Criteria andIsFeeNotBetween(String value1, String value2) {
            addCriterion("IS_FEE not between", value1, value2, "isFee");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account_order
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 11 10:14:35 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account_order
     *
     * @mbggenerated Thu Jan 11 10:14:35 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}