package com.yl.recon.core.entity.fileinfo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
/**
 * @author 聚合支付有限公司
 * @since 2018年01月18
 * @version V1.0.0
 */
public class ReconFileInfoExtendExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public ReconFileInfoExtendExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(Long value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(Long value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(Long value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(Long value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(Long value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<Long> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<Long> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(Long value1, Long value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(Long value1, Long value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andHeaderIsNull() {
            addCriterion("header is null");
            return (Criteria) this;
        }

        public Criteria andHeaderIsNotNull() {
            addCriterion("header is not null");
            return (Criteria) this;
        }

        public Criteria andHeaderEqualTo(String value) {
            addCriterion("header =", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderNotEqualTo(String value) {
            addCriterion("header <>", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderGreaterThan(String value) {
            addCriterion("header >", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderGreaterThanOrEqualTo(String value) {
            addCriterion("header >=", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderLessThan(String value) {
            addCriterion("header <", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderLessThanOrEqualTo(String value) {
            addCriterion("header <=", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderLike(String value) {
            addCriterion("header like", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderNotLike(String value) {
            addCriterion("header not like", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderIn(List<String> values) {
            addCriterion("header in", values, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderNotIn(List<String> values) {
            addCriterion("header not in", values, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderBetween(String value1, String value2) {
            addCriterion("header between", value1, value2, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderNotBetween(String value1, String value2) {
            addCriterion("header not between", value1, value2, "header");
            return (Criteria) this;
        }

        public Criteria andFooterIsNull() {
            addCriterion("footer is null");
            return (Criteria) this;
        }

        public Criteria andFooterIsNotNull() {
            addCriterion("footer is not null");
            return (Criteria) this;
        }

        public Criteria andFooterEqualTo(String value) {
            addCriterion("footer =", value, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterNotEqualTo(String value) {
            addCriterion("footer <>", value, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterGreaterThan(String value) {
            addCriterion("footer >", value, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterGreaterThanOrEqualTo(String value) {
            addCriterion("footer >=", value, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterLessThan(String value) {
            addCriterion("footer <", value, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterLessThanOrEqualTo(String value) {
            addCriterion("footer <=", value, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterLike(String value) {
            addCriterion("footer like", value, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterNotLike(String value) {
            addCriterion("footer not like", value, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterIn(List<String> values) {
            addCriterion("footer in", values, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterNotIn(List<String> values) {
            addCriterion("footer not in", values, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterBetween(String value1, String value2) {
            addCriterion("footer between", value1, value2, "footer");
            return (Criteria) this;
        }

        public Criteria andFooterNotBetween(String value1, String value2) {
            addCriterion("footer not between", value1, value2, "footer");
            return (Criteria) this;
        }

        public Criteria andTotalFlagIsNull() {
            addCriterion("total_flag is null");
            return (Criteria) this;
        }

        public Criteria andTotalFlagIsNotNull() {
            addCriterion("total_flag is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFlagEqualTo(String value) {
            addCriterion("total_flag =", value, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagNotEqualTo(String value) {
            addCriterion("total_flag <>", value, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagGreaterThan(String value) {
            addCriterion("total_flag >", value, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagGreaterThanOrEqualTo(String value) {
            addCriterion("total_flag >=", value, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagLessThan(String value) {
            addCriterion("total_flag <", value, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagLessThanOrEqualTo(String value) {
            addCriterion("total_flag <=", value, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagLike(String value) {
            addCriterion("total_flag like", value, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagNotLike(String value) {
            addCriterion("total_flag not like", value, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagIn(List<String> values) {
            addCriterion("total_flag in", values, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagNotIn(List<String> values) {
            addCriterion("total_flag not in", values, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagBetween(String value1, String value2) {
            addCriterion("total_flag between", value1, value2, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andTotalFlagNotBetween(String value1, String value2) {
            addCriterion("total_flag not between", value1, value2, "totalFlag");
            return (Criteria) this;
        }

        public Criteria andDelimiterIsNull() {
            addCriterion("delimiter is null");
            return (Criteria) this;
        }

        public Criteria andDelimiterIsNotNull() {
            addCriterion("delimiter is not null");
            return (Criteria) this;
        }

        public Criteria andDelimiterEqualTo(String value) {
            addCriterion("delimiter =", value, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterNotEqualTo(String value) {
            addCriterion("delimiter <>", value, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterGreaterThan(String value) {
            addCriterion("delimiter >", value, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterGreaterThanOrEqualTo(String value) {
            addCriterion("delimiter >=", value, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterLessThan(String value) {
            addCriterion("delimiter <", value, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterLessThanOrEqualTo(String value) {
            addCriterion("delimiter <=", value, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterLike(String value) {
            addCriterion("delimiter like", value, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterNotLike(String value) {
            addCriterion("delimiter not like", value, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterIn(List<String> values) {
            addCriterion("delimiter in", values, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterNotIn(List<String> values) {
            addCriterion("delimiter not in", values, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterBetween(String value1, String value2) {
            addCriterion("delimiter between", value1, value2, "delimiter");
            return (Criteria) this;
        }

        public Criteria andDelimiterNotBetween(String value1, String value2) {
            addCriterion("delimiter not between", value1, value2, "delimiter");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeIsNull() {
            addCriterion("interface_info_code is null");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeIsNotNull() {
            addCriterion("interface_info_code is not null");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeEqualTo(String value) {
            addCriterion("interface_info_code =", value, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeNotEqualTo(String value) {
            addCriterion("interface_info_code <>", value, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeGreaterThan(String value) {
            addCriterion("interface_info_code >", value, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeGreaterThanOrEqualTo(String value) {
            addCriterion("interface_info_code >=", value, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeLessThan(String value) {
            addCriterion("interface_info_code <", value, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeLessThanOrEqualTo(String value) {
            addCriterion("interface_info_code <=", value, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeLike(String value) {
            addCriterion("interface_info_code like", value, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeNotLike(String value) {
            addCriterion("interface_info_code not like", value, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeIn(List<String> values) {
            addCriterion("interface_info_code in", values, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeNotIn(List<String> values) {
            addCriterion("interface_info_code not in", values, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeBetween(String value1, String value2) {
            addCriterion("interface_info_code between", value1, value2, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceInfoCodeNotBetween(String value1, String value2) {
            addCriterion("interface_info_code not between", value1, value2, "interfaceInfoCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeIsNull() {
            addCriterion("bank_order_code is null");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeIsNotNull() {
            addCriterion("bank_order_code is not null");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeEqualTo(String value) {
            addCriterion("bank_order_code =", value, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeNotEqualTo(String value) {
            addCriterion("bank_order_code <>", value, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeGreaterThan(String value) {
            addCriterion("bank_order_code >", value, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bank_order_code >=", value, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeLessThan(String value) {
            addCriterion("bank_order_code <", value, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("bank_order_code <=", value, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeLike(String value) {
            addCriterion("bank_order_code like", value, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeNotLike(String value) {
            addCriterion("bank_order_code not like", value, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeIn(List<String> values) {
            addCriterion("bank_order_code in", values, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeNotIn(List<String> values) {
            addCriterion("bank_order_code not in", values, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeBetween(String value1, String value2) {
            addCriterion("bank_order_code between", value1, value2, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andBankOrderCodeNotBetween(String value1, String value2) {
            addCriterion("bank_order_code not between", value1, value2, "bankOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeIsNull() {
            addCriterion("interface_order_code is null");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeIsNotNull() {
            addCriterion("interface_order_code is not null");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeEqualTo(String value) {
            addCriterion("interface_order_code =", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeNotEqualTo(String value) {
            addCriterion("interface_order_code <>", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeGreaterThan(String value) {
            addCriterion("interface_order_code >", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("interface_order_code >=", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeLessThan(String value) {
            addCriterion("interface_order_code <", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("interface_order_code <=", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeLike(String value) {
            addCriterion("interface_order_code like", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeNotLike(String value) {
            addCriterion("interface_order_code not like", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeIn(List<String> values) {
            addCriterion("interface_order_code in", values, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeNotIn(List<String> values) {
            addCriterion("interface_order_code not in", values, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeBetween(String value1, String value2) {
            addCriterion("interface_order_code between", value1, value2, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeNotBetween(String value1, String value2) {
            addCriterion("interface_order_code not between", value1, value2, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(String value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(String value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(String value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(String value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(String value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(String value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLike(String value) {
            addCriterion("amount like", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotLike(String value) {
            addCriterion("amount not like", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<String> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<String> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(String value1, String value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(String value1, String value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andFeeIsNull() {
            addCriterion("fee is null");
            return (Criteria) this;
        }

        public Criteria andFeeIsNotNull() {
            addCriterion("fee is not null");
            return (Criteria) this;
        }

        public Criteria andFeeEqualTo(String value) {
            addCriterion("fee =", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotEqualTo(String value) {
            addCriterion("fee <>", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThan(String value) {
            addCriterion("fee >", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThanOrEqualTo(String value) {
            addCriterion("fee >=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThan(String value) {
            addCriterion("fee <", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThanOrEqualTo(String value) {
            addCriterion("fee <=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLike(String value) {
            addCriterion("fee like", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotLike(String value) {
            addCriterion("fee not like", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeIn(List<String> values) {
            addCriterion("fee in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotIn(List<String> values) {
            addCriterion("fee not in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeBetween(String value1, String value2) {
            addCriterion("fee between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotBetween(String value1, String value2) {
            addCriterion("fee not between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andTransTimeIsNull() {
            addCriterion("trans_time is null");
            return (Criteria) this;
        }

        public Criteria andTransTimeIsNotNull() {
            addCriterion("trans_time is not null");
            return (Criteria) this;
        }

        public Criteria andTransTimeEqualTo(String value) {
            addCriterion("trans_time =", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeNotEqualTo(String value) {
            addCriterion("trans_time <>", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeGreaterThan(String value) {
            addCriterion("trans_time >", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeGreaterThanOrEqualTo(String value) {
            addCriterion("trans_time >=", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeLessThan(String value) {
            addCriterion("trans_time <", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeLessThanOrEqualTo(String value) {
            addCriterion("trans_time <=", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeLike(String value) {
            addCriterion("trans_time like", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeNotLike(String value) {
            addCriterion("trans_time not like", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeIn(List<String> values) {
            addCriterion("trans_time in", values, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeNotIn(List<String> values) {
            addCriterion("trans_time not in", values, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeBetween(String value1, String value2) {
            addCriterion("trans_time between", value1, value2, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeNotBetween(String value1, String value2) {
            addCriterion("trans_time not between", value1, value2, "transTime");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("bank_name is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("bank_name is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("bank_name =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("bank_name <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("bank_name >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("bank_name >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("bank_name <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("bank_name <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("bank_name like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("bank_name not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("bank_name in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("bank_name not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("bank_name between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("bank_name not between", value1, value2, "bankName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 18 09:50:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recon_file_info_extend
     *
     * @mbggenerated Thu Jan 18 09:50:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}