package com.yl.recon.core.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ReconExceptionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public ReconExceptionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(Long value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(Long value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(Long value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(Long value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(Long value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<Long> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<Long> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(Long value1, Long value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(Long value1, Long value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdIsNull() {
            addCriterion("recon_order_id is null");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdIsNotNull() {
            addCriterion("recon_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdEqualTo(String value) {
            addCriterion("recon_order_id =", value, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdNotEqualTo(String value) {
            addCriterion("recon_order_id <>", value, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdGreaterThan(String value) {
            addCriterion("recon_order_id >", value, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("recon_order_id >=", value, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdLessThan(String value) {
            addCriterion("recon_order_id <", value, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdLessThanOrEqualTo(String value) {
            addCriterion("recon_order_id <=", value, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdLike(String value) {
            addCriterion("recon_order_id like", value, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdNotLike(String value) {
            addCriterion("recon_order_id not like", value, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdIn(List<String> values) {
            addCriterion("recon_order_id in", values, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdNotIn(List<String> values) {
            addCriterion("recon_order_id not in", values, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdBetween(String value1, String value2) {
            addCriterion("recon_order_id between", value1, value2, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconOrderIdNotBetween(String value1, String value2) {
            addCriterion("recon_order_id not between", value1, value2, "reconOrderId");
            return (Criteria) this;
        }

        public Criteria andReconDateIsNull() {
            addCriterion("recon_date is null");
            return (Criteria) this;
        }

        public Criteria andReconDateIsNotNull() {
            addCriterion("recon_date is not null");
            return (Criteria) this;
        }

        public Criteria andReconDateEqualTo(Date value) {
            addCriterionForJDBCDate("recon_date =", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("recon_date <>", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateGreaterThan(Date value) {
            addCriterionForJDBCDate("recon_date >", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("recon_date >=", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateLessThan(Date value) {
            addCriterionForJDBCDate("recon_date <", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("recon_date <=", value, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateIn(List<Date> values) {
            addCriterionForJDBCDate("recon_date in", values, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("recon_date not in", values, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("recon_date between", value1, value2, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("recon_date not between", value1, value2, "reconDate");
            return (Criteria) this;
        }

        public Criteria andReconTypeIsNull() {
            addCriterion("recon_type is null");
            return (Criteria) this;
        }

        public Criteria andReconTypeIsNotNull() {
            addCriterion("recon_type is not null");
            return (Criteria) this;
        }

        public Criteria andReconTypeEqualTo(String value) {
            addCriterion("recon_type =", value, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeNotEqualTo(String value) {
            addCriterion("recon_type <>", value, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeGreaterThan(String value) {
            addCriterion("recon_type >", value, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeGreaterThanOrEqualTo(String value) {
            addCriterion("recon_type >=", value, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeLessThan(String value) {
            addCriterion("recon_type <", value, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeLessThanOrEqualTo(String value) {
            addCriterion("recon_type <=", value, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeLike(String value) {
            addCriterion("recon_type like", value, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeNotLike(String value) {
            addCriterion("recon_type not like", value, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeIn(List<String> values) {
            addCriterion("recon_type in", values, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeNotIn(List<String> values) {
            addCriterion("recon_type not in", values, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeBetween(String value1, String value2) {
            addCriterion("recon_type between", value1, value2, "reconType");
            return (Criteria) this;
        }

        public Criteria andReconTypeNotBetween(String value1, String value2) {
            addCriterion("recon_type not between", value1, value2, "reconType");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Double value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Double value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Double value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Double value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Double value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Double> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Double> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Double value1, Double value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Double value1, Double value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeIsNull() {
            addCriterion("trade_order_code is null");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeIsNotNull() {
            addCriterion("trade_order_code is not null");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeEqualTo(String value) {
            addCriterion("trade_order_code =", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeNotEqualTo(String value) {
            addCriterion("trade_order_code <>", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeGreaterThan(String value) {
            addCriterion("trade_order_code >", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("trade_order_code >=", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeLessThan(String value) {
            addCriterion("trade_order_code <", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("trade_order_code <=", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeLike(String value) {
            addCriterion("trade_order_code like", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeNotLike(String value) {
            addCriterion("trade_order_code not like", value, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeIn(List<String> values) {
            addCriterion("trade_order_code in", values, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeNotIn(List<String> values) {
            addCriterion("trade_order_code not in", values, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeBetween(String value1, String value2) {
            addCriterion("trade_order_code between", value1, value2, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andTradeOrderCodeNotBetween(String value1, String value2) {
            addCriterion("trade_order_code not between", value1, value2, "tradeOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeIsNull() {
            addCriterion("interface_order_code is null");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeIsNotNull() {
            addCriterion("interface_order_code is not null");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeEqualTo(String value) {
            addCriterion("interface_order_code =", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeNotEqualTo(String value) {
            addCriterion("interface_order_code <>", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeGreaterThan(String value) {
            addCriterion("interface_order_code >", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("interface_order_code >=", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeLessThan(String value) {
            addCriterion("interface_order_code <", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("interface_order_code <=", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeLike(String value) {
            addCriterion("interface_order_code like", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeNotLike(String value) {
            addCriterion("interface_order_code not like", value, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeIn(List<String> values) {
            addCriterion("interface_order_code in", values, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeNotIn(List<String> values) {
            addCriterion("interface_order_code not in", values, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeBetween(String value1, String value2) {
            addCriterion("interface_order_code between", value1, value2, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andInterfaceOrderCodeNotBetween(String value1, String value2) {
            addCriterion("interface_order_code not between", value1, value2, "interfaceOrderCode");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeIsNull() {
            addCriterion("recon_exception_type is null");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeIsNotNull() {
            addCriterion("recon_exception_type is not null");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeEqualTo(String value) {
            addCriterion("recon_exception_type =", value, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeNotEqualTo(String value) {
            addCriterion("recon_exception_type <>", value, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeGreaterThan(String value) {
            addCriterion("recon_exception_type >", value, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("recon_exception_type >=", value, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeLessThan(String value) {
            addCriterion("recon_exception_type <", value, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeLessThanOrEqualTo(String value) {
            addCriterion("recon_exception_type <=", value, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeLike(String value) {
            addCriterion("recon_exception_type like", value, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeNotLike(String value) {
            addCriterion("recon_exception_type not like", value, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeIn(List<String> values) {
            addCriterion("recon_exception_type in", values, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeNotIn(List<String> values) {
            addCriterion("recon_exception_type not in", values, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeBetween(String value1, String value2) {
            addCriterion("recon_exception_type between", value1, value2, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andReconExceptionTypeNotBetween(String value1, String value2) {
            addCriterion("recon_exception_type not between", value1, value2, "reconExceptionType");
            return (Criteria) this;
        }

        public Criteria andHandleStatusIsNull() {
            addCriterion("handle_status is null");
            return (Criteria) this;
        }

        public Criteria andHandleStatusIsNotNull() {
            addCriterion("handle_status is not null");
            return (Criteria) this;
        }

        public Criteria andHandleStatusEqualTo(String value) {
            addCriterion("handle_status =", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusNotEqualTo(String value) {
            addCriterion("handle_status <>", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusGreaterThan(String value) {
            addCriterion("handle_status >", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusGreaterThanOrEqualTo(String value) {
            addCriterion("handle_status >=", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusLessThan(String value) {
            addCriterion("handle_status <", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusLessThanOrEqualTo(String value) {
            addCriterion("handle_status <=", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusLike(String value) {
            addCriterion("handle_status like", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusNotLike(String value) {
            addCriterion("handle_status not like", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusIn(List<String> values) {
            addCriterion("handle_status in", values, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusNotIn(List<String> values) {
            addCriterion("handle_status not in", values, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusBetween(String value1, String value2) {
            addCriterion("handle_status between", value1, value2, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusNotBetween(String value1, String value2) {
            addCriterion("handle_status not between", value1, value2, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkIsNull() {
            addCriterion("handle_remark is null");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkIsNotNull() {
            addCriterion("handle_remark is not null");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkEqualTo(String value) {
            addCriterion("handle_remark =", value, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkNotEqualTo(String value) {
            addCriterion("handle_remark <>", value, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkGreaterThan(String value) {
            addCriterion("handle_remark >", value, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("handle_remark >=", value, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkLessThan(String value) {
            addCriterion("handle_remark <", value, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkLessThanOrEqualTo(String value) {
            addCriterion("handle_remark <=", value, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkLike(String value) {
            addCriterion("handle_remark like", value, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkNotLike(String value) {
            addCriterion("handle_remark not like", value, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkIn(List<String> values) {
            addCriterion("handle_remark in", values, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkNotIn(List<String> values) {
            addCriterion("handle_remark not in", values, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkBetween(String value1, String value2) {
            addCriterion("handle_remark between", value1, value2, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andHandleRemarkNotBetween(String value1, String value2) {
            addCriterion("handle_remark not between", value1, value2, "handleRemark");
            return (Criteria) this;
        }

        public Criteria andOperIsNull() {
            addCriterion("oper is null");
            return (Criteria) this;
        }

        public Criteria andOperIsNotNull() {
            addCriterion("oper is not null");
            return (Criteria) this;
        }

        public Criteria andOperEqualTo(String value) {
            addCriterion("oper =", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperNotEqualTo(String value) {
            addCriterion("oper <>", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperGreaterThan(String value) {
            addCriterion("oper >", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperGreaterThanOrEqualTo(String value) {
            addCriterion("oper >=", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperLessThan(String value) {
            addCriterion("oper <", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperLessThanOrEqualTo(String value) {
            addCriterion("oper <=", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperLike(String value) {
            addCriterion("oper like", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperNotLike(String value) {
            addCriterion("oper not like", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperIn(List<String> values) {
            addCriterion("oper in", values, "oper");
            return (Criteria) this;
        }

        public Criteria andOperNotIn(List<String> values) {
            addCriterion("oper not in", values, "oper");
            return (Criteria) this;
        }

        public Criteria andOperBetween(String value1, String value2) {
            addCriterion("oper between", value1, value2, "oper");
            return (Criteria) this;
        }

        public Criteria andOperNotBetween(String value1, String value2) {
            addCriterion("oper not between", value1, value2, "oper");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recon_exception
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 02 18:16:52 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}