package com.yl.recon.core.mybatis.mapper;

import com.yl.recon.core.entity.fileinfo.ReconFileInfoExtendExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import com.yl.recon.core.entity.fileinfo.ReconFileInfoExtend;
/**
 * @author 聚合支付有限公司
 * @since 2018年01月18
 * @version V1.0.0
 */
public interface ReconFileInfoExtendMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
    int insert(@Param("reconFileInfoExtend") ReconFileInfoExtend reconFileInfoExtend);
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
    int insertSelective(@Param("reconFileInfoExtend") ReconFileInfoExtend reconFileInfoExtend);
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
    int insertList(@Param("reconFileInfoExtends") List<ReconFileInfoExtend> reconFileInfoExtends);
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
    int update(@Param("reconFileInfoExtend") ReconFileInfoExtend reconFileInfoExtend);
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
	int countByExample(ReconFileInfoExtendExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
	int deleteByExample(ReconFileInfoExtendExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
	int deleteByPrimaryKey(Long code);


	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
	List<ReconFileInfoExtend> selectByExample(ReconFileInfoExtendExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
	ReconFileInfoExtend selectByPrimaryKey(Long code);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
	int updateByExampleSelective(@Param("record") ReconFileInfoExtend record, @Param("example") ReconFileInfoExtendExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
	int updateByExample(@Param("record") ReconFileInfoExtend record, @Param("example") ReconFileInfoExtendExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
	int updateByPrimaryKeySelective(ReconFileInfoExtend record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info_extend
	 *
	 * @mbggenerated Thu Jan 18 09:18:36 CST 2018
	 */
	int updateByPrimaryKey(ReconFileInfoExtend record);
}
