package com.yl.recon.core.mybatis.mapper;


import com.lefu.commons.utils.Page;
import com.yl.recon.core.entity.fileinfo.ReconFileInfo;
import com.yl.recon.core.entity.fileinfo.ReconFileInfoExample;

import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 * @author 聚合支付有限公司
 * @version V1.0.0
 * @since 2018年01月06
 */
public interface ReconFileInfoMapper {

	int insert(@Param("reconFileInfo") ReconFileInfo reconFileInfo);

	int insertSelective(@Param("reconFileInfo") ReconFileInfo reconFileInfo);

	int insertList(@Param("reconFileInfos") List <ReconFileInfo> reconFileInfos);

	int update(@Param("reconFileInfo") ReconFileInfo reconFileInfo);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info
	 *
	 * @mbggenerated Sat Jan 13 14:26:56 CST 2018
	 */
	int countByExample(ReconFileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info
	 *
	 * @mbggenerated Sat Jan 13 14:26:56 CST 2018
	 */
	int deleteByExample(ReconFileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info
	 *
	 * @mbggenerated Sat Jan 13 14:26:56 CST 2018
	 */
	int deleteByPrimaryKey(Long code);


	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info
	 *
	 * @mbggenerated Sat Jan 13 14:26:56 CST 2018
	 */
	List <ReconFileInfo> selectByExample(ReconFileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info
	 *
	 * @mbggenerated Sat Jan 13 14:26:56 CST 2018
	 */
	ReconFileInfo selectByPrimaryKey(Long code);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info
	 *
	 * @mbggenerated Sat Jan 13 14:26:56 CST 2018
	 */
	int updateByExampleSelective(@Param("record") ReconFileInfo record, @Param("example") ReconFileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info
	 *
	 * @mbggenerated Sat Jan 13 14:26:56 CST 2018
	 */
	int updateByExample(@Param("record") ReconFileInfo record, @Param("example") ReconFileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info
	 *
	 * @mbggenerated Sat Jan 13 14:26:56 CST 2018
	 */
	int updateByPrimaryKeySelective(ReconFileInfo record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table recon_file_info
	 *
	 * @mbggenerated Sat Jan 13 14:26:56 CST 2018
	 */
	int updateByPrimaryKey(ReconFileInfo record);

	/**
	 * 分页通道对账文件查询
	 *
	 * @param page
	 * @param params
	 * @return
	 */
	List <com.yl.recon.api.core.bean.ReconFileInfo> findAllReconFileInfo(@Param("page") Page page, @Param("params") Map <String, Object> params);

	/**
	 * 通过id通道对账文件查询
	 *
	 * @param params
	 * @return
	 */
	com.yl.recon.api.core.bean.ReconFileInfo findReconFileInfoByCode(@Param("params") Map <String, Object> params);

	/**
	 * 不分页:通道对账文件查询
	 *
	 * @param params
	 * @return
	 */
	List <com.yl.recon.api.core.bean.ReconFileInfo> findReconFileInfo(@Param("params") Map <String, Object> params);




}