package com.yl.recon.core.mybatis.mapper;

import com.lefu.commons.utils.Page;
import com.yl.recon.core.entity.ReconException;
import com.yl.recon.core.entity.ReconExceptionExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;
/**
 * @author 聚合支付有限公司
 * @since 2018年01月08
 * @version V1.0.0
 */
@Repository
public interface ReconExceptionMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    int countByExample(ReconExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    int deleteByExample(ReconExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    int deleteByPrimaryKey(Long code);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    List<ReconException> selectByExample(ReconExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    ReconException selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReconException record, @Param("example") ReconExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    int updateByExample(@Param("record") ReconException record, @Param("example") ReconExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    int updateByPrimaryKeySelective(ReconException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recon_exception
     *
     * @mbggenerated Sat Sep 02 18:16:52 CST 2017
     */
    int updateByPrimaryKey(ReconException record);

	/**
	 * 插入
	 * @param reconException
	 * @return
	 */
	int insert(@Param("reconException") ReconException reconException);

	/**
	 * 选择插入
	 * @param reconException
	 * @return
	 */
	int insertSelective(@Param("reconException") ReconException reconException);

	/**
	 * 批量插入
	 * @param reconExceptions
	 * @return
	 */
	int insertList(@Param("reconExceptions") List<ReconException> reconExceptions);

	/**
	 * 更新
	 * @param reconException
	 * @return
	 */
	int update(@Param("reconException") ReconException reconException);

	/**
	 * 分页查询所有
	 * @param page
	 * @param params
	 * @return
	 */
	List<com.yl.recon.api.core.bean.ReconException> findAll(@Param("page") Page page, @Param("params") Map<String, Object> params);
	/**
	 * 查询所有
 	 * @param params
	 * @return
	 */
	List<com.yl.recon.api.core.bean.ReconException> queryAll(@Param("params") Map<String, Object> params);


}