package com.yl.recon.core.mybatis.mapper;

import com.yl.recon.core.entity.order.TotalOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import com.yl.recon.core.entity.order.TotalOrder;
import org.springframework.stereotype.Repository;
/**
 * @author 聚合支付有限公司
 * @since 2018年01月11
 * @version V1.0.0
 */
@Repository
public interface TotalOrderMapper {
	/**
	 * 插入
	 * @param totalOrder
	 * @return
	 */
    int insert(@Param("totalOrder") TotalOrder totalOrder);

	/**
	 * 插入属性不空的
	 * @param totalOrder
	 * @return
	 */
	int insertSelective(@Param("totalOrder") TotalOrder totalOrder);

	/**
	 * 批量插入
	 * @param totalOrders
	 * @return
	 */
    int insertList(@Param("totalOrders") List<TotalOrder> totalOrders);

	/**
	 * 更新
	 * @param totalOrder
	 * @return
	 */
	int update(@Param("totalOrder") TotalOrder totalOrder);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table total_order
	 *
	 * @mbggenerated Fri Jan 12 16:15:46 CST 2018
	 */
	int countByExample(TotalOrderExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table total_order
	 *
	 * @mbggenerated Fri Jan 12 16:15:46 CST 2018
	 */
	int deleteByExample(TotalOrderExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table total_order
	 *
	 * @mbggenerated Fri Jan 12 16:15:46 CST 2018
	 */
	int deleteByPrimaryKey(Long code);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table total_order
	 *
	 * @mbggenerated Fri Jan 12 16:15:46 CST 2018
	 */
	List<TotalOrder> selectByExample(TotalOrderExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table total_order
	 *
	 * @mbggenerated Fri Jan 12 16:15:46 CST 2018
	 */
	TotalOrder selectByPrimaryKey(Long code);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table total_order
	 *
	 * @mbggenerated Fri Jan 12 16:15:46 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TotalOrder record, @Param("example") TotalOrderExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table total_order
	 *
	 * @mbggenerated Fri Jan 12 16:15:46 CST 2018
	 */
	int updateByExample(@Param("record") TotalOrder record, @Param("example") TotalOrderExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table total_order
	 *
	 * @mbggenerated Fri Jan 12 16:15:46 CST 2018
	 */
	int updateByPrimaryKeySelective(TotalOrder record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table total_order
	 *
	 * @mbggenerated Fri Jan 12 16:15:46 CST 2018
	 */
	int updateByPrimaryKey(TotalOrder record);
}
